export type RootStackParamList = {
  HomeScreen: undefined;
  LoginPersonal: undefined;
  LoginAluno: undefined;
  RegisterPersonal: undefined;
  EditPersonal: { cpf: string };
  DeletePersonal: undefined;
  ViewPersonal: undefined;
  RegisterAluno: undefined;
  EditAluno: { cpf: string };
  DeleteAluno: undefined;
  ViewAluno: undefined;
  ViewContratosAluno: undefined;
  RegisterServico: undefined;
  EditServico: { servicoId: number };
  DeleteServico: undefined;
  ViewServico: undefined;
  Personal: undefined;
  Aluno: undefined;
  Servico: undefined;
};
